name: CI

on: 
  push: 
    branches: 
      - main

jobs: 
  tests: 
    runs-on: ubuntu-latest
    steps:
      - name: Do tests
        run: echo "Start tests"
      


  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Do linters
        run: echo "Start linters"
      
